<!--Scroll to top-->
<script src="{{ asset('assets/js/jquery.js')}}"></script>
<script src="{{ asset('assets/js/popper.min.js')}}"></script>
<script src="{{ asset('assets/js/jquery-ui.js')}}"></script>
<script src="{{ asset('assets/asset/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('assets/js/jquery.fancybox.js')}}"></script>
<script src="{{ asset('assets/js/parallax.min.js')}}"></script>
<script src="{{ asset('assets/js/jquery.paroller.min.js')}}"></script>
<script src="{{ asset('assets/js/owl.js')}}"></script>
<script src="{{ asset('assets/js/wow.js')}}"></script>
<script src="{{ asset('assets/js/nav-tool.js')}}"></script>
<script src="{{ asset('assets/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{ asset('assets/js/main.js')}}"></script>
<script src="{{ asset('assets/js/swiper.min.js')}}"></script>
<script src="{{ asset('assets/js/appear.js')}}"></script>
<script src="{{ asset('assets/js/script.js')}}"></script>
<script src="{{ asset('assets/js/color-settings.js')}}"></script>